// Docs generator (FR11, section 4.7). One source of truth (the manifests) feeds
// both the live /help command and docs/COMMANDS.md.
//
//   node scripts/generate-docs.js          -> write docs/COMMANDS.md
//   node scripts/generate-docs.js --check  -> exit non-zero if it is stale (CI)

import { readFile, writeFile, mkdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { loadRegistry } from "../src/registry.js";
import { buildHelpCommand } from "../src/help.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUTPUT_PATH = join(__dirname, "..", "docs", "COMMANDS.md");

function usage(command) {
  const args = (command.options ?? [])
    .map((o) => (o.required ? `<${o.name}>` : `[${o.name}]`))
    .join(" ");
  return args ? `/${command.name} ${args}` : `/${command.name}`;
}

function commandRow(command, moduleName) {
  const reply = command.ephemeral ? "private" : "public";
  return `| \`${usage(command)}\` | ${command.description} | ${reply} | ${moduleName} |`;
}

function render(modules, commandMap) {
  const lines = [];
  lines.push("# BamfBot commands");
  lines.push("");
  lines.push("<!-- AUTO-GENERATED by scripts/generate-docs.js - do not edit by hand. -->");
  lines.push("<!-- Run `npm run docs` after changing any module manifest. -->");
  lines.push("");
  lines.push("| Command | Description | Reply | Module |");
  lines.push("|---------|-------------|-------|--------|");

  // Core-owned commands first.
  const help = buildHelpCommand();
  lines.push(commandRow({ ...help, ephemeral: true }, "_core_"));

  // Module commands, alphabetical by command name.
  const entries = [...commandMap.entries()].sort((a, b) => a[0].localeCompare(b[0]));
  for (const [, { module, command }] of entries) {
    lines.push(commandRow(command, `\`${module.name}\``));
  }

  lines.push("");
  lines.push("## Modules");
  lines.push("");
  if (modules.length === 0) {
    lines.push("_No modules loaded._");
  } else {
    for (const module of [...modules].sort((a, b) => a.name.localeCompare(b.name))) {
      lines.push(`### \`${module.name}\` v${module.version}`);
      lines.push("");
      lines.push(module.description ?? "");
      lines.push("");
      lines.push(`- Language: ${module.language ?? "unknown"}`);
      const perms = module.discord?.botPermissions ?? [];
      lines.push(`- Bot permissions: ${perms.length ? perms.join(", ") : "none"}`);
      const intents = module.discord?.gatewayIntents ?? [];
      lines.push(`- Gateway intents: ${intents.length ? intents.join(", ") : "none"}`);
      lines.push("");
    }
  }

  return lines.join("\n") + "\n";
}

async function main() {
  const check = process.argv.includes("--check");
  const { modules, commandMap } = await loadRegistry();
  const generated = render(modules, commandMap);

  if (check) {
    let existing = null;
    try {
      existing = await readFile(OUTPUT_PATH, "utf8");
    } catch {
      // missing file counts as stale
    }
    if (existing !== generated) {
      console.error(
        "docs/COMMANDS.md is out of date. Run `npm run docs` and commit the result."
      );
      process.exitCode = 1;
      return;
    }
    console.log("docs/COMMANDS.md is up to date.");
    return;
  }

  await mkdir(dirname(OUTPUT_PATH), { recursive: true });
  await writeFile(OUTPUT_PATH, generated, "utf8");
  console.log(`Wrote ${OUTPUT_PATH}`);
}

main().catch((error) => {
  console.error("Docs generation failed:", error.message);
  process.exitCode = 1;
});
