// Docs generator (FR11, section 4.7). One source of truth (the manifests) feeds
// both the live /help command and docs/COMMANDS.md.
//
//   node scripts/generate-docs.js          -> write docs/COMMANDS.md
//   node scripts/generate-docs.js --check  -> exit non-zero if it is stale (CI)

import { readFile, writeFile, mkdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { loadRegistry, ROOT_COMMAND_NAME } from "../src/registry.js";
import { buildHelpSubcommand } from "../src/help.js";
import { buildRequirement, describeRequirement } from "../src/access.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUTPUT_PATH = join(__dirname, "..", "docs", "COMMANDS.md");

function optionArgs(options) {
  return (options ?? [])
    .filter((o) => o.type !== "subcommand" && o.type !== "subcommand_group")
    .map((o) => (o.required ? `<${o.name}>` : `[${o.name}]`))
    .join(" ");
}

/**
 * One table row per invocable path. A command with subcommands expands to a row
 * per subcommand (`/bamf threads list`); a plain command is a single row
 * (`/bamf hello`).
 */
function accessCell(access) {
  const req = buildRequirement({
    permissions: access?.permissions ?? [],
    roles: access?.roles ?? [],
  });
  return req ? describeRequirement(req) : "anyone";
}

function commandRows(command, moduleName) {
  const reply = command.ephemeral ? "private" : "public";
  const subs = (command.options ?? []).filter((o) => o.type === "subcommand");

  if (subs.length > 0) {
    return subs.map((sub) => {
      const args = optionArgs(sub.options);
      const usage = args
        ? `/${ROOT_COMMAND_NAME} ${command.name} ${sub.name} ${args}`
        : `/${ROOT_COMMAND_NAME} ${command.name} ${sub.name}`;
      return `| \`${usage}\` | ${sub.description} | ${reply} | ${accessCell(sub.access ?? command.access)} | ${moduleName} |`;
    });
  }

  const args = optionArgs(command.options);
  const usage = args
    ? `/${ROOT_COMMAND_NAME} ${command.name} ${args}`
    : `/${ROOT_COMMAND_NAME} ${command.name}`;
  return [`| \`${usage}\` | ${command.description} | ${reply} | ${accessCell(command.access)} | ${moduleName} |`];
}

function render(modules, commandMap) {
  const lines = [];
  lines.push("# BamfBot commands");
  lines.push("");
  lines.push("<!-- AUTO-GENERATED by scripts/generate-docs.js - do not edit by hand. -->");
  lines.push("<!-- Run `npm run docs` after changing any module manifest. -->");
  lines.push("");
  lines.push(`Every command is a subcommand of \`/${ROOT_COMMAND_NAME}\`.`);
  lines.push("");
  lines.push("| Command | Description | Reply | Access | Module |");
  lines.push("|---------|-------------|-------|--------|--------|");

  // Core-owned commands first.
  const help = buildHelpSubcommand();
  lines.push(...commandRows({ ...help, ephemeral: true }, "_core_"));

  // Module commands, alphabetical by command name.
  const entries = [...commandMap.entries()].sort((a, b) => a[0].localeCompare(b[0]));
  for (const [, { module, command }] of entries) {
    lines.push(...commandRows(command, `\`${module.name}\``));
  }

  lines.push("");
  lines.push("## Modules");
  lines.push("");
  if (modules.length === 0) {
    lines.push("_No modules loaded._");
  } else {
    for (const module of [...modules].sort((a, b) => a.name.localeCompare(b.name))) {
      lines.push(`### \`${module.name}\` v${module.version}`);
      lines.push("");
      lines.push(module.description ?? "");
      lines.push("");
      lines.push(`- Availability: ${module.__restricted ? "server-specific (restricted)" : "universal"}`);
      lines.push(`- Language: ${module.language ?? "unknown"}`);
      const perms = module.discord?.botPermissions ?? [];
      lines.push(`- Bot permissions: ${perms.length ? perms.join(", ") : "none"}`);
      const intents = module.discord?.gatewayIntents ?? [];
      lines.push(`- Gateway intents: ${intents.length ? intents.join(", ") : "none"}`);
      lines.push("");
    }
  }

  return lines.join("\n") + "\n";
}

async function main() {
  const check = process.argv.includes("--check");
  const { modules, commandMap } = await loadRegistry();
  const generated = render(modules, commandMap);

  if (check) {
    let existing = null;
    try {
      existing = await readFile(OUTPUT_PATH, "utf8");
    } catch {
      // missing file counts as stale
    }
    if (existing !== generated) {
      console.error(
        "docs/COMMANDS.md is out of date. Run `npm run docs` and commit the result."
      );
      process.exitCode = 1;
      return;
    }
    console.log("docs/COMMANDS.md is up to date.");
    return;
  }

  await mkdir(dirname(OUTPUT_PATH), { recursive: true });
  await writeFile(OUTPUT_PATH, generated, "utf8");
  console.log(`Wrote ${OUTPUT_PATH}`);
}

main().catch((error) => {
  console.error("Docs generation failed:", error.message);
  process.exitCode = 1;
});
